# -*- coding: utf-8 -*-
"""citra_original.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cc_Ds5aie9m1VZv7m0Em8E_NPKzjmmK9

A. citra original
1. kita harus memanggil library python package yang di perlukan dengan cara    
mengimportkan library python package nya
"""

import imageio
import matplotlib.pyplot as plt
import numpy as np

"""2. masukkan kode untuk memasukkan citra original"""

gambar_original = imageio.imread("didi4.jpg")

plt.imshow(gambar_original)
plt.title("Citra original")
plt.show()