# -*- coding: utf-8 -*-
"""Citra original to citra grayscale.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15i3_MqVCCEnBen-UXf3gIzwRWzO9eylE

A. citra original to citra gyrscale
1. kita harus memanggil library python package yang di perlukan dengan cara    
mengimportkan library python package nya
"""

import imageio
import matplotlib.pyplot as plt
import numpy as np

"""2. masukkan kode untuk memasukkan citra original terlebih dahulu"""

gambar_original = imageio.imread("didi4.jpg")

plt.imshow(gambar_original)
plt.title("Citra original")
plt.show()

"""3. selanjutnya masukkan kode segmentasi citra digital yang kita inginkan, di sini saya memakai segmentasi citra digital grayscale"""

imgGrayscale = np.zeros((gambar_original.shape[0], gambar_original.shape[1], 3), dtype=np.uint8)
for y in range(0, gambar_original.shape[0]):
  for x in range(0, gambar_original.shape[1]):
    r = gambar_original[y][x][0]
    g = gambar_original[y][x][1]
    b = gambar_original[y][x][2]
    gr = ( int(r) + int(g) + int(b) ) / 3
    imgGrayscale[y][x] = (gr, gr, gr)
        
plt.imshow(imgGrayscale)
plt.title("Citra Grayscale")
plt.show()