# -*- coding: utf-8 -*-
"""citra original to citra segmentasi noise gaussian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HQ3QT99eJtlARi2EQ81pmHqDW2Hasbti

B. Citra Original to citra metode NoiseGaussian
   1. kita harus memanggil library python package yang di perlukan dengan cara    
mengimportkan library python package nya
"""

import imageio
import matplotlib.pyplot as plt
import numpy as np

"""2. masukkan kode untuk memasukkan citra original terlebih dahulu"""

citra_asli = imageio.imread("didi4.jpg")

plt.imshow(citra_asli)
plt.title("citra original")
plt.show()

"""3. selanjutnya masukkan kode segmentasi citra digital yang kita inginkan, di sini saya memakai segmentasi citra digital metode NoiseGaussian"""

imgNoiseGaussian = np.zeros((citra_asli.shape[0], citra_asli.shape[1], 3), dtype=np.uint8)

# Add noise
for y in range(0, citra_asli.shape[0]):
    for x in range(0, citra_asli.shape[1]):
        xg = citra_asli[y][x][0]
        xb = xg
        nr = np.random.randint(0,100)
        if nr < 20:
            ns = np.random.randint(0,256) - 128
            xb = int(xg + ns)
            if xb < 0:
                xb = -xb
            if xb > 255:
                xb = 255
        imgNoiseGaussian[y][x] = (xb, xb, xb)

plt.imshow(imgNoiseGaussian)
plt.title("Citra Noise Gaussian")
plt.show()